name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

jobs:
  add_label:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Awaiting Changes"
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Approved"
